language: python
python:
  - 2.7
  - 3.6
  - 3.7
dist: xenial
services:
  - xvfb  # X Virtual FrameBuffer (enables plotting in a headless environment)
before_install:  # optional dependencies
  - pip install codecov
install:
  - pip install -e '.[interact,pld,bls,test]'
script:  # how to run the tests?
  - pytest --remote-data
after_success:
  - codecov

