image: Visual Studio 2017 # required to install pybind11 (celerite dependency)

build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"
  - "ECHO %PATH%"
  - where conda
  - conda config --set always_yes yes --set changeps1 no
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy astropy scipy matplotlib requests tqdm pandas bokeh ipython scikit-learn pybind11 pytest pytest-cov pytest-remotedata"
  - activate test-environment
  - conda install -c astropy astroquery
  - pip install sphinx_rtd_theme
  - pip install codecov
  - pip install numpydoc
  - python setup.py develop

test_script:
  - pytest --remote-data
