trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        pytest.options: ''
        pip.command: 'pip install -e .[test]'
      Python36:
        python.version: '3.6'
        pytest.options: ''
        pip.command: 'pip install -e .[all,test]'
      Python37_WithRemoteData:
        python.version: '3.7'
        pytest.options: '--remote-data'
        pip.command: 'pip install -e .[all,test]'
      Python37_WithoutOptionalDependencies:
        python.version: '3.7'
        pytest.options: ''
        pip.command: 'pip install -e .[test]'

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
      conda create --yes --quiet --name myEnvironment
      source activate myEnvironment
      conda install --yes --quiet --name myEnvironment numpy scipy astropy
    displayName: Setup anaconda
  - template: .azure-template.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37_WithRemoteData:
        python.version: '3.7'
        pytest.options: '--remote-data'
        pip.command: 'pip install -e .[all,test]'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - template: .azure-template.yml

- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
        pytest.options: ''
        pip.command: 'pip install -e .[all,test]'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - template: .azure-template.yml
